EBandPlannerROS:
  Ctrl_Rate : 20
  differential_drive: True
  max_acceleration: 0.5
  max_vel_lin: 0.75
  max_vel_th: 0.7
  min_vel_lin: 0.02
  min_vel_th: 0.0
  xy_goal_tolerance: 0.09
  yaw_goal_tolerance: 0.02

